/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/madhahib": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the supported schools */
        get: operations["listMadhahib"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve a case under one school */
        post: operations["solve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve a case across all four schools */
        post: operations["compare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved cases */
        get: operations["listCases"];
        put?: never;
        /** Save a case */
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Fetch a saved case */
        get: operations["getCase"];
        put?: never;
        post?: never;
        /** Delete a saved case */
        delete: operations["deleteCase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export a result as JSON or PDF */
        post: operations["export"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a natural-language case description (experimental trial tier)
         * @description Optional, non-authoritative feature behind a feature flag. The returned proposal must be confirmed by a human before the deterministic engine is run.
         */
        post: operations["parseCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft a plain language explanation (experimental trial tier)
         * @description Optional, non-authoritative feature behind a feature flag. The engine result is the ground truth; the prose only rephrases it and is rejected if it contradicts the numbers.
         */
        post: operations["explain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
        };
        Madhhab: {
            /** @enum {string} */
            name: "Hanafi" | "Maliki" | "Shafii" | "Hanbali";
        };
        /**
         * @description A map of heir relation label to the count present.
         * @example {
         *       "husband": 1,
         *       "son": 2,
         *       "daughter": 1
         *     }
         */
        Heirs: {
            [key: string]: number;
        };
        Estate: {
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            funeral?: number;
            /** Format: int64 */
            debts?: number;
            /** Format: int64 */
            bequests?: number;
            heirsConsentToExcessBequest?: boolean;
        };
        CaseInput: {
            /** @enum {string} */
            deceasedSex: "male" | "female";
            estate?: components["schemas"]["Estate"];
            heirs: components["schemas"]["Heirs"];
            /** @enum {string} */
            madhhab?: "Hanafi" | "Maliki" | "Shafii" | "Hanbali";
        };
        SolveRequest: components["schemas"]["CaseInput"] & {
            /** @enum {string} */
            madhhab: "Hanafi" | "Maliki" | "Shafii" | "Hanbali";
        };
        HeirShare: {
            relation: string;
            count: number;
            /** @example 1/4 */
            fraction: string;
            /** Format: int64 */
            parts?: number;
            /** @example 250 */
            amount: string;
        };
        DerivationStep: {
            stage: string;
            relation?: string;
            detail?: string;
            reference?: string;
            fraction?: string;
        };
        SolveResult: {
            madhhab: string;
            distributable: string;
            /** Format: int64 */
            base: number;
            shares: components["schemas"]["HeirShare"][];
            excluded?: string[];
            specialCase?: string;
            awl?: boolean;
            radd?: boolean;
            residue?: string;
            needsReview?: boolean;
            reviewNotes?: string[];
            derivation?: components["schemas"]["DerivationStep"][];
        };
        Comparison: {
            results: {
                [key: string]: components["schemas"]["SolveResult"];
            };
            divergences?: string[];
        };
        SaveCaseRequest: {
            name: string;
            input: components["schemas"]["SolveRequest"];
        };
        SavedCase: {
            id: string;
            name: string;
            input: components["schemas"]["SolveRequest"];
            /** Format: date-time */
            createdAt?: string;
        };
        ParseRequest: {
            /** @description Natural-language description of the inheritance case (Arabic or English). */
            text: string;
        };
        ParseProposal: {
            /** @enum {string} */
            deceasedSex: "male" | "female";
            heirs: components["schemas"]["Heirs"];
            /** @description Optional clarifying notes from the model. */
            notes?: string;
        };
        Explanation: {
            text: string;
            consistent: boolean;
            experimental?: boolean;
        };
        Error: {
            error: string;
        };
    };
    responses: {
        /** @description The request was invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listMadhahib: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The supported madhahib. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Madhhab"][];
                };
            };
        };
    };
    solve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description The computed distribution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    compare: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseInput"];
            };
        };
        responses: {
            /** @description The per-school results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listCases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The saved cases. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedCase"][];
                };
            };
        };
    };
    createCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCaseRequest"];
            };
        };
        responses: {
            /** @description The saved case. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedCase"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The saved case. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedCase"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The case was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    export: {
        parameters: {
            query: {
                format: "json" | "pdf";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description The exported document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveResult"];
                    "application/pdf": string;
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    parseCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description The parsed proposal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseProposal"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The trial feature is disabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The model output could not be validated as a legal case. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    explain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description The explanation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explanation"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The trial feature is disabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
